scrape_configs:
  - job_name: 'Genesis_10x_Prometheus'
    scrape_interval: 60s
    metrics_path: /customer/v1/privileged/metrics
    scheme: https
    basic_auth:
      username: service_role
      password: 'sb_secret_XOXE1Wb3peAWJqdSDgVLCw_CZj2AlJn'
    static_configs:
      - targets: ['duuycxgqbhrqwapnjhk.supabase.co:443']
